### GET usage Id Parm
GET http://localhost:8080/products/3
Accept: application/json

### GET all Products
GET http://localhost:8080/products
Accept: application/json

### Create Products
POST http://localhost:8080/products
Accept: application/json
Content-Type: application/json

{
      "name": "AC TRADING GUILDE",
      "purchase_price": 5,
      "selling_price": 10,
      "stock": 100
}

### UPDATE Products usage Id Parm
PUT http://localhost:8080/products/15
Accept: application/json
Content-Type: application/json

{
  "name": "nuke hirosima",
  "purchase_price": 5,
  "selling_price": 10,
  "stock": 100
}

### DELETE Products usage Id Parm
PUT http://localhost:8080/products/8
Accept: application/json