### POST register

POST http://localhost:8080/api/auth/register
Accept: application/json
Content-Type: application/json

{
    "user_name":"admin",
    "password":"admin123",
    "name":"admin ganteng"
}
###